#!/bin/sh
#
###############################################################################
#
# github_repos_list retrieves the list of Git repositories present at a give github.com account.
#
###############################################################################
# Authors:
# Marco De Bortoli <mdebortoli@inviqa.com>
# Marco Massari Calderone <mmassari@inviqa.com>
#
# Copyright (C) 2012 Inviqa UK Ltd
#
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see http://www.gnu.org/licenses/.
#
###############################################################################


GITHUB_CREDENTIALS=~/.github_info
if [ -f $GITHUB_CREDENTIALS ]; then
    source $GITHUB_CREDENTIALS
    # '.github_info' must contain the following information
    # USERNAME="<username>"
    # PASSWORD="<password>"
    # ORGANIZATION="<organisation>"
    # 
    # protect the GitHub login information:
    # - storing the file in the home folder of the user(s) that will execute the script
    # - defining the ownershit of '.github_info' to <user>:<user>
    # - defining the permissions of '.github_info' to 600
    #
else
    # default values
    USERNAME="username"
    PASSWORD="password"
    ORGANIZATION="organisation"
fi

# Arrays definition

NEPO=""
SSH_URL=""
NAME=""

# used to suppress curl noise
STDERR_REDIR='/dev/null'

GIT_URL="curl -u \"$USERNAME:$PASSWORD\" https://api.github.com/orgs/$ORGANIZATION/repos"

names=($(curl -u "$USERNAME:$PASSWORD" https://api.github.com/orgs/$ORGANIZATION/repos 2> /dev/null | grep name | cut -f4 -d'"' ))

ssh_urls=($(curl -u "$USERNAME:$PASSWORD" https://api.github.com/orgs/$ORGANIZATION/repos 2> /dev/null | grep ssh_url | cut -f4 -d'"' ))

elements=${#names[@]}

for (( i=0; i<${elements}; i++ ));
do
        echo "name=${names[$i]} ssh_url=${ssh_urls[$i]}"
done




