#!/bin/bash
function _echo() {
  echo -e "\033[1m\n${1}\n\033[0m";
  tput sgr0;
}
function _get_variables() {
  # first set the script defauls

  SERVICE_ENABLE='';
  SUDO_ENABLE=false;
  SOCKSPROXY_REMOTE_SERVER='';
  SOCKSPROXY_LOCAL_SERVER='localhost';
  SOCKSPROXY_PORT='8080';
  NETWORK_SERVICE='Ethernet';

  local VERBOSE=false;
  local USER_CONFIGS=~/.socksproxyrc;
  # SERVICE_ENABLE='on';
  # SOCKSPROXY_REMOTE_SERVER='remote_server_name_or_ip';
  # SOCKSPROXY_REMOTE_SERVER_PORT='8080';
  # SOCKSPROXY_LOCAL_SERVER='localhost';
  # SOCKSPROXY_LOCAL_SERVER_port='8080';
  # NETWORK_SERVICE='Ethernet';

  # the checks if the user has it's own defaults
  if [ -f ${USER_CONFIGS} ]; then
    source ${USER_CONFIGS}
  fi

  # then checks if any inline parameters are passed to override the defauts
  while [[ "${#}" > 0 ]]; do
    option="${1}";
    case $option in
      -v|--verbose)
        VERBOSE=true;
      ;;
      --sudo)
        SUDO_ENABLE=true;
      ;;
      --enable)
        SERVICE_ENABLE="on";
      ;;
      --disable)
        SERVICE_ENABLE="off";
      ;;
      -r|--remote)
        SOCKSPROXY_REMOTE_SERVER="${2}";
        shift
      ;;
      -l|--local)
        SOCKSPROXY_LOCAL_SERVER="${2}";
        shift
      ;;
      -p|--port)
        SOCKSPROXY_PORT="${2}";
        shift
      ;;
      -n|--network)
        NETWORK_SERVICE="${2}";
        shift
       #"Wi-Fi"
       #"Ethernet 1"
       #"iPhone USB"
      ;;
      *)
      # unknown option
      _echo "UNKNOWN PARAMETER: == ${1} =="
      return 1
      ;;
  esac
    #evaluate the next PARAMETER
    shift
  done

  if ${VERBOSE} ; then
    _print_paramaters;
  fi
}

function _print_paramaters() {
  _echo "SUDO_ENABLE: $SUDO_ENABLE
SERVICE_ENABLE: $SERVICE_ENABLE
SOCKSPROXY_REMOTE_SERVER: $SOCKSPROXY_REMOTE_SERVER
SOCKSPROXY_LOCAL_SERVER: $SOCKSPROXY_LOCAL_SERVER
SOCKSPROXY_PORT: $SOCKSPROXY_PORT
NETWORK_SERVICE: $NETWORK_SERVICE";
}

function _remoteproxy_connect() {
  local SSH_COMMAND="ssh -f -N -T -M $SOCKSPROXY_REMOTE_SERVER -D $SOCKSPROXY_PORT"
  eval $SSH_COMMAND 2>&1 >> /dev/null
  _echo "CONNECTED TO $SOCKSPROXY_REMOTE_SERVER PROXY SERVER ON PORT $SOCKSPROXY_PORT";
}
function _remoteproxy_disconnect() {
  # requires
  # ControlPath ~/.ssh/xxxxx.ctl
  # in .ssh/config

  local SSH_COMMAND="ssh -T -O 'exit' $SOCKSPROXY_REMOTE_SERVER"
  eval $SSH_COMMAND  2>&1 >> /dev/null
  _echo "PROXY SERVER DISCONNECTED";
}
function _socksproxy_activate() {
  #with parameters passed
  local COMMAND="networksetup -setsocksfirewallproxy "$NETWORK_SERVICE" $SOCKSPROXY_LOCAL_SERVER $SOCKSPROXY_PORT"
  eval $SUDO $COMMAND
  _echo "PROXY SERVER ENABLED"
}
function _socksproxy_deactivate() {
  local COMMAND="networksetup -setsocksfirewallproxystate "$NETWORK_SERVICE" off"
  eval $SUDO $COMMAND
  _echo "PROXY SERVER DISABLED"
}

function manage_proxy() {

  if ! _get_variables "${@}" ; then
    # brakes the execution if some unknown parameters are detected
    # therefore _get_variables has returned "1"
    _echo "OPERATION ABORTED";
    exit 1
  fi
  if $SUDO_ENABLE;then
    SUDO="sudo"
  fi
  if [[  "${SERVICE_ENABLE}" == "on" ]]; then
    _remoteproxy_connect;
    _socksproxy_activate;
  elif [[ "${SERVICE_ENABLE}" == "off" ]]; then
    _socksproxy_deactivate;
    _remoteproxy_disconnect;
  fi

}

manage_proxy "${@}";
