#!/bin/sh
while true; do
        DEFAULT_URL="http://incubator.inviqa.com:8080//plugin/jenkinswalldisplay/walldisplay.html?viewName=Projects&jenkinsUrl=http%3A%2F%2Fincubator.inviqa.com%3A8080%2F"

	# Clean up previously running apps, gracefully at first then harshly
	killall -TERM chromium 2>/dev/null;
	killall -TERM matchbox-window-manager 2>/dev/null;
	sleep 2;
	killall -9 chromium 2>/dev/null;
	killall -9 matchbox-window-manager 2>/dev/null;

	# Clean out existing profile information
	rm -rf /home/pi/.cache;
	#rm -rf /home/pi/.config;
	rm -rf /home/pi/.pki;

	# Generate the bare minimum to keep Chromium happy!
	mkdir -p /home/pi/.config/chromium/Default
	sqlite3 /home/pi/.config/chromium/Default/Web\ Data "CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR); INSERT INTO meta VALUES('version','46'); CREATE TABLE keywords (foo INTEGER);";

	# Disable DPMS / Screen blanking
	xset -dpms
	xset s off

	# Reset the framebuffer's colour-depth
	fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );

	# Hide the cursor (move it to the bottom-right, comment out if you want mouse interaction)
	xwit -root -warp $( cat /sys/module/*fb*/parameters/fbwidth ) $( cat /sys/module/*fb*/parameters/fbheight )
        
        # starts thw x11vnc (VNC) session
        x11vnc -logfile $HOME/.x11vnc.log -viewonly -shared -forever -rfbport 5900 -avahi -display :0 -usepw -bg

	# Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
	#matchbox-window-manager -use_titlebar no -use_cursor no &
	#matchbox-window-manager &
	matchbox-window-manager -use_titlebar no &
	
	# makes sure that the  DEFAULT_URL is reacheable before starting the browser
        # otherwise the browser could hang on a white page as it canno retrieve the content from the source site
	until curl -# --connect-timeout 3 $DEFAULT_URL 2> /dev/null  > /dev/null; do
                sleep 1
        done
        # Start the browser (See http://peter.sh/experiments/chromium-command-line-switches/)
        chromium  --enable-offline-auto-reload --app=$DEFAULT_URL	#chromium 
done;
